name: 🤖 Build

on:
  push:

jobs:
  build-docker:
    name: Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: keystone-web:latest
          outputs: type=docker,dest=/tmp/keystone-web.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: keystone-web-docker
          path: /tmp/keystone-web.tar
