name: 🎯 Pull Request

on:
  pull_request:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/Build.yml

  test:
    name: Test
    needs: build
    uses: ./.github/workflows/Test.yml

  report-pr-status:
    name: Report PR Status
    runs-on: ubuntu-latest
    needs: [ test ]
    if: always()

    steps:
      - name: Check PR status
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
