name: 🤖 QA

on:
  workflow_call:

jobs:
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript-typescript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: /language:javascript-typescript

  codacy:
    name: Codacy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          upload: true

  report-qa-status:
    name: Report QA Status
    runs-on: ubuntu-latest
    needs: [ codeql, codacy ]
    if: always()

    steps:
      - name: Check QA status
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') }}
        run: exit 1
